#! /usr/bin/env python

import time
import subprocess
import daemon

def main():
    title = '"$(echo %s | cut -c1-10)"'
    args = ['/usr/bin/rem', '-z',
            '-kurxvt +rv -hold -name notsink -title %s -e echo %%s &' % title]
    with daemon.DaemonContext():
        while True:
            subprocess.call(args)
            time.sleep(60)

if __name__ == '__main__':
    main()
